language: java
jdk: openjdk11
services:
  - docker
install: true
cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: build
      script: ./mvnw --no-transfer-progress -P helfomat-web,helfomat-web-ui,helfomat-import clean install
    - stage: build and push docker images
      if: branch IN (master, develop) AND type=push
      script: ./travis/helfomat-web_dockerBuildAndPublish.sh