language: java
jdk: openjdk8
services:
  - docker
install: true
cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: build
      script: ./mvnw clean install
    - stage: build and push docker image
      script: ./travis/helfomat-web_dockerBuildAndPublish.sh