security:
  oauth2:
    client:
      client-id: helfomat-import
      client-secret:
      access-token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
      token-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect

helfomat:
  importer:
    web-api-url: http://helfomat-web/helf-o-mat

keycloak:
  realm: helfomat
  auth-server-url: http://keycloak/auth