security:
  oauth2:
    client:
      client-id: helfomat-import
      client-secret: 526f9f2c-34e8-405d-85c5-35b708c77bb1
      access-token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
      token-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect

helfomat:
  importer:
    web-api-url: http://localhost:8080/helf-o-mat

keycloak:
  realm: helfomat
  auth-server-url: http://localhost:8085/auth