- block:
  - name: import certificate from helfenkannjeder.de to keystore
    java_cert:
      cert_url: helfenkannjeder.de
      cert_port: 443
      keystore_path: /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts
      keystore_pass: changeit
      state: present
  - name: create app directory
    file:
      name: "{{ helfomat.appDirectory }}"
      state: directory
      owner: "{{ helfomat.user }}"
      group: "{{ helfomat.group }}"
  - name: write configuration file
    copy:
      content: "{{ helfomat_config }}"
      dest: "{{ helfomat.appDirectory }}/helfomat.conf"
    notify: restart helfomat
  - name: check if previous version is already there
    stat:
      path: "{{ helfomat.appDirectory }}/helfomat.jar"
    register: old_jar
  - name: enable writing the jar
    file:
      name: "{{ helfomat.appDirectory }}/helfomat.jar"
      state: file
      attributes: e
    when: old_jar.stat.exists == True
  - name: copy the jar to the server
    copy:
      src: ../helfomat-web/target/helfomat.jar
      dest: "{{ helfomat.appDirectory }}/helfomat.jar"
      owner: "{{ helfomat.user }}"
      group: "{{ helfomat.group }}"
      mode: 0500
    notify: restart helfomat
  - name: disable writing the jar
    file:
      name: "{{ helfomat.appDirectory }}/helfomat.jar"
      attributes: ie
  - name: create symlink for service execution
    file:
      src: "{{ helfomat.appDirectory }}/helfomat.jar"
      dest: "/etc/init.d/{{ helfomat.serviceName }}"
      state: link
  - name: enable helfomat service
    service:
      name: "{{ helfomat.serviceName }}"
      enabled: yes