apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helfomat-import
spec:
  schedule: "0 1 * * *"

  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace

  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: helfomat-import
              image: helfenkannjedercontainer.azurecr.io/helf-o-mat.import
              imagePullPolicy: IfNotPresent

              resources:
                limits:
                  cpu: 400m
                  memory: 600Mi
                requests:
                  cpu: 200m
                  memory: 400Mi

              env:
                - name: SPRING_PROFILES_INCLUDE
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-import-config
                      key: helfomat.import.spring.profiles

                - name: SPRING_EVENT_DATASOURCE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-import-config
                      key: helfomat.import.db.events.url
                - name: SPRING_EVENT_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-import-db-secret
                      key: helfomat.import.postgres.user
                - name: SPRING_EVENT_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-import-db-secret
                      key: helfomat.import.postgres.password

                - name: SPRING_ELASTICSEARCH_REST_URIS
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.web.elastic.resturis

                - name: GOOGLEMAPS_API-KEY
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-web-secret
                      key: helfomat.web.googlemaps.api.key

                - name: HELFOMAT_IMPORTER_WEB-API-URL
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-import-config
                      key: helfomat.import.helfomat-web.url
                - name: SECURITY_OAUTH2_CLIENT_CLIENT-SECRET
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-import-secret
                      key: helfomat.import.helfomat-web.oauth-client

                - name: KEYCLOAK_AUTH-SERVER-URL
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-import-config
                      key: helfomat.import.keycloak.url

                - name: SPRING_MAIL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.mail.host
                - name: SPRING_MAIL_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.mail.port
                - name: SPRING_MAIL_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-web-secret
                      key: helfomat.mail.username
                - name: SPRING_MAIL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: helfomat-web-secret
                      key: helfomat.mail.password
                - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.mail.properties.mail.smtp.auth
                - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.mail.properties.mail.smtp.starttls.enable
                - name: HELFOMAT_EMAIL_SENDER
                  valueFrom:
                    configMapKeyRef:
                      name: helfomat-web-config
                      key: helfomat.mail.sender

          restartPolicy: Never
