apiVersion: apps/v1
kind: Deployment
metadata:
  name: helfomat-web-ui
spec:
  selector:
    matchLabels:
      app: helfomat-web-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: helfomat-web-ui
    spec:
      containers:
        - name: helfomat-web-ui
          image: helfenkannjedercontainer.azurecr.io/helf-o-mat.web-ui
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi

          ports:
            - containerPort: 80
