apiVersion: v1
kind: Service
metadata:
  name: helfomat-web-service
  labels:
    app: helfomat-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - name: helfomat-web-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helfomat-web
