spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  event:
    datasource:
      url: jdbc:postgresql://localhost/helfenkannjeder
      username: helfenkannjeder
      password: helfenkannjeder

  elasticsearch:
    rest:
      uris: http://localhost:9200

security:
  keycloak:
    client:
      client-id: helfomat-web-profile-admin
      client-secret: a7188212-d414-4f0e-afd2-71605acf9c4d

helfomat:
  locale: de_DE
  domain: http://localhost:4200/

keycloak:
  realm: helfenkannjeder
  resource: helfenkannjeder-web-ui
  auth-server-url: http://localhost:8085/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username