server:
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain

elasticsearch:
  index: helfomat
  type:
    organization: organization

googlemaps:
  api-key: ReplaceMe

helfomat.picture:
  picture-folder: pictures/
  picture-sizes:
  - name: icon
    width: 84
  - name: teaser
    width: 1000
    height: 300
  - name: medium
    width: 300

spring.servlet.multipart:
  max-file-size: 20MB
  max-request-size: 20MB


logging:
  level:
    root: ERROR
    de.helfenkannjeder: DEBUG