spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/helfenkannjeder
    username: helfenkannjeder
    password: helfenkannjeder

  data:
    elasticsearch:
      cluster-name: application
      cluster-nodes: localhost:9300

  elasticsearch:
    jest:
      uris: http://localhost:9200
      read-timeout: 10000

  batch:
    job:
      enabled: false

elasticsearch:
  index: helfomat
  type:
    organisation: organisation

crawler:
  thw:
    domain: http://thw.de/
    resultsPerPage: 10
    httpRequestTimeout: 60000
    logo: https://www.helfenkannjeder.de/uploads/pics/THW-Logo_BReg.png
    mapPin: blue-pushpin.png

googlemaps:
  api-key: ReplaceMe

helfomat:
  picture-folder: pictures/
  questions:
  - id: "2863d2db-264f-4d3d-98fb-8a48a6c1a882"
    question: "Möchtest Du gerne Einsatzfahrzeuge - ggf. auch mit Blaulicht und Martinshorn - fahren?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "YES"
    - phrase: "Schnelleinsatzgruppe" # ASB / DRK
      answer: "YES"
    - phrase: "Bergungsgruppe" # THW
      answer: "MAYBE"
    - phrase: "DLRG-Ortsgruppe"
      answer: "MAYBE"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "NO"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"
    - phrase: "Ortsverein allgemein"
      answer: "MAYBE"
    position: 1

  - id: "8dd070ed-a9de-42af-a017-57a096cf8ec1"
    question: "Möchtest Du Dich in medizinischer Hilfe ausbilden lassen und diese leisten?"
    defaultAnswer: "MAYBE"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Rettungsdienst" # ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"
    position: 2

  - id: "6487dd30-8d1a-4421-b424-2d822cb13e32"
    question: "Du hast keine Angst vor Feuer, nur Respekt. Möchtest Du lernen, wie man es löscht?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "YES"
    position: 3

  - id: "35a19221-8fbf-45fb-9443-65a43aae9013"
    question: "Hast Du Interesse daran, Menschen bei Verkehrsunfällen aus Fahrzeugen zu retten?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "YES"
    - phrase: "Rettungsdienst" # ASB / DRK
      answer: "MAYBE"
    - phrase: "Bergungsgruppe" # THW
      answer: "MAYBE"
    position: 4

  - id: "58aca3fe-1783-42ff-81d6-43212d76ce04"
    question: "Kannst Du sehr kurzfristig, ggf. auch innerhalb Deiner Arbeitszeiten, für Einsätze zur Verfügung stehen?"
    defaultAnswer: "MAYBE"
    groups:
    - organisationType: "FF"
      answer: "YES"
    - phrase: "Schnelleinsatzgruppe" # ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "NO"
    position: 5

  - id: "89342f97-4a0e-457b-994b-5a4851618acc"
    question: "Ist Kochen eine Deiner Leidenschaften?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Feldkochherd"
      answer: "YES"
    - phrase: "Logistik-Verpflegungstrupp"
      answer: "YES"
    - phrase: "Betreuung" # DLRG / ASB / DRK
      answer: "MAYBE"
    position: 6

  - id: "e30180fd-bd93-4409-a5f4-8b7eb32948da"
    question: "Möchtest Du aktiv im Naturschutz mitwirken?"
    defaultAnswer: "NO"
    groups:
    - phrase: "ABC-Zug" # FW
      answer: "YES"
    - phrase: "Umwelt" # DLRG
      answer: "YES"
    - phrase: "Ölwehr" # THW
      answer: "YES"
    - phrase: "Umweltschutz" # THW
      answer: "YES"
    position: 7

  - id: "3e3042fa-beca-4d18-bb0c-f6f9a9d8f68f"
    question: "Bist Du handwerklich begabt? Den Umgang mit Kettensäge und Trennschleifer möchtest Du erlernen?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "MAYBE"
    - phrase: "Bergungsgruppe" # THW
      answer: "YES"
    position: 8

  - id: "44d1132f-3407-4387-808d-47368c8d7ffc"
    question: "Hast Du was für Wassersport übrig? Boot fahren, Retten von Menschen aus Gewässern?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Wassergefahren" # THW
      answer: "YES"
    - phrase: "Rettungsschwimm" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Rettungstaucher" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "wasserrettung" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Boot" # DLRG / ASB / DRK / FW / THW
      answer: "YES"
    position: 9

  - id: "b6788fa7-a360-4b65-8055-193c4c40d1f4"
    question: "Magst Du die Bergwelt? Kannst Du Dir vorstellen, hier Menschen zu retten?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"
    - phrase: "Höhenrettung" # ASB / DRK / THW
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"
    position: 10

  - id: "ae4cdb0c-c35f-42fe-8996-599bfffc8fc2"
    question: "Betreuung von unverletzten Menschen, mit ihnen sprechen, die wichtigsten Dinge des Lebens organisieren und verteilen - Dein Ding?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "MAYBE"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "MAYBE"
    - phrase: "Kriseninterventionsteam" # ASB / DRK
      answer: "YES"
    - phrase: "Betreuung" # DLRG / ASB / DRK
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"
    position: 11

  - id: "c9204024-1399-4b34-b7a4-6919c09cdc41"
    question: "Möchtest Du aktiv als Besatzungsmitglied eines Rettungs- oder Krankentransportwagens mitfahren?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"
    position: 12

  - id: "0d76d16a-c640-40ec-af4e-2111ad36ee46"
    question: "Bist Du handwerklich interessiert und kannst Strom, Heizung, Wasser, etc. in Notunterkünften installieren?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Bergungsgruppe"
      answer: "YES"
    - phrase: "Technik und Sicherheit" # ASB / DRK
      answer: "MAYBE"
    - organisationType: "FF"
      answer: "MAYBE"
    position: 13

  - id: "18662fa9-a854-4174-9ea9-37bb08c65484"
    question: "Fährst Du gerne Motorrad? Kommst Du auch mit etwas größeren Maschinen klar?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Motorrad"
      answer: "YES"
    - phrase: "ATV/Quad"
      answer: "YES"
    position: 14

  - id: "e025aa16-4b69-42db-9fce-d34792d99a77"
    question: "Gebrochene Knochen schocken Dich nicht - auf die richtige Behandlung kommt es an. Interesse?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"
    position: 15

  - id: "82113a83-d99a-4a63-89eb-9e5f4268917b"
    question: "Radlader-, Baggerfahren - schwere Baumaschinen fahren?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Räumen" # THW
      answer: "YES"
    - phrase: "Bagger" # THW
      answer: "YES"
    - phrase: "Drehleiter"
      answer: "MAYBE"
    position: 16

  - id: "4813a002-9c0e-4f29-af0c-26be7c197bea"
    question: "Klettern, Bergsteigen, Verletzte retten - auch aus der Kletterwand? Wäre das etwas für Dich?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Drehleiter" # FW
      answer: "YES"
    - phrase: "Höhenrettung" # FW / THW
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"
    - phrase: "Hubschraubergestützte Wasserrettung" # DLRG / ASB / DRK
      answer: "MAYBE"
    position: 17

  - id: "2e82c293-1f6a-4b4c-8366-f773d42f1caf"
    question: "Deinen Hund zum Suchhund ausbilden, mit ihm vermisste Menschen orten und retten? Interesse?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Ortung Typ A"
      answer: "YES"
    - phrase: "Fachgruppe Ortung"
      answer: "YES"
    - phrase: "Rettungshunde" # DLRG / ASB / BW / DRK
      answer: "YES"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "YES"
    position: 18
  picture-sizes:
  - name: icon
    width: 84
  - name: teaser
    width: 1000
    height: 300
  - name: medium
    width: 300
  admin-users:
  - username: admin
    password: ${random.value}
    print-password: true

logging:
  file: ${logging.path:${LOG_TEMP:${java.io.tmpdir:/tmp}}}/helfenkannjeder-helfomat.log

  level:
    de.helfenkannjeder: DEBUG