server:
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/helfenkannjeder
    username: helfenkannjeder
    password: helfenkannjeder

  data:
    elasticsearch:
      cluster-name: application
      cluster-nodes: localhost:9300

  elasticsearch:
    jest:
      uris: http://localhost:9200
      read-timeout: 10000

  batch:
    job:
      enabled: false

elasticsearch:
  index: helfomat
  type:
    organisation: organisation

crawler:
  thw:
    domain: http://thw.de/
    resultsPerPage: 10
    httpRequestTimeout: 60000
    mapPin: blue-pushpin.png

googlemaps:
  api-key: ReplaceMe

helfomat:
  picture-folder: pictures/
  autoImport:
    enabled: true
    schedule: "0 0 3 1/1 * *"
  questions:
  - id: "8dd070ed-a9de-42af-a017-57a096cf8ec1"
    question: "Möchtest Du Dich in medizinischer Hilfe ausbilden lassen und diese leisten?"
    description: "Wenn in Folge z. B. eines Unfalls Menschen ernsthafte Verletzungen erlitten haben, benötigen sie Deine Hilfe. Du bist für das Erkennen von Gefahren für den Betroffenen sowie die Durchführung der richtigen Maßnahmen verantwortlich."
    defaultAnswer: "MAYBE"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Rettungsdienst" # ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"

  - id: "6487dd30-8d1a-4421-b424-2d822cb13e32"
    question: "Du hast keine Angst vor Feuer, nur Respekt. Möchtest Du lernen, wie man es löscht?"
    description: "Zum effizienten Löschen von Bränden ist überlegtes Handeln erforderlich: Erlaubt die aktuelle Situation, einen Gebäudebrand von innen unter schwerem Atemschutz zu bekämpfen oder ist ein Außenangriff zu bevorzugen?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "YES"

  - id: "35a19221-8fbf-45fb-9443-65a43aae9013"
    question: "Hast Du Interesse daran, Menschen bei Verkehrsunfällen aus Fahrzeugen zu retten?"
    description: "Zwei Fahrzeuge sind zusammengestoßen, die Fahrzeugführer eingeklemmt und nicht ansprechbar. Hauptziel der Rettung ist es nun, die verunglückten Personen in kürzestmöglicher Zeit aus ihrem Fahrzeug zu befreien und einer intensivmedizinischen Betreuung in einem Krankenhaus zuzuführen."
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "YES"
    - phrase: "Rettungsdienst" # ASB / DRK
      answer: "MAYBE"
    - phrase: "Bergungsgruppe" # THW
      answer: "MAYBE"

  - id: "58aca3fe-1783-42ff-81d6-43212d76ce04"
    question: "Kannst Du sehr kurzfristig, ggf. auch innerhalb Deiner Arbeitszeiten, für Einsätze zur Verfügung stehen?"
    description: "Brände oder Verkehrsunfälle erfordern schnelles Handeln. Hier solltest Du in der Lage sein, Deinen Arbeitsplatz zu verlassen. Es finden sich aber genügend Möglichkeiten, die entsprechende Vorlaufzeiten erlauben."
    defaultAnswer: "MAYBE"
    groups:
    - organisationType: "FF"
      answer: "YES"
    - phrase: "Schnelleinsatzgruppe" # ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "NO"

  - id: "89342f97-4a0e-457b-994b-5a4851618acc"
    question: "Ist Kochen eine Deiner Leidenschaften?"
    description: "Könntest Du Dir vorstellen, die Verpflegung von wenigen bis einigen hundert Einsatzkräften zu verantworten, ohne dass dabei der Feldkochherd ruiniert wird?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Feldkochherd"
      answer: "YES"
    - phrase: "Logistik-Verpflegungstrupp"
      answer: "YES"
    - phrase: "Betreuung" # DLRG / ASB / DRK
      answer: "MAYBE"

  - id: "e30180fd-bd93-4409-a5f4-8b7eb32948da"
    question: "Möchtest Du aktiv im Naturschutz mitwirken?"
    description: "Neben der Beseitigung von Umweltschäden nach Unfällen (z. B. Ölverschmutzung von Stränden) leisten Einsatzorganisationen auch beispielsweise bei der Renaturierung von Steinbrüchen oder dem Anlegen von Wanderwegen einen wertvollen Beitrag."
    defaultAnswer: "NO"
    groups:
    - phrase: "ABC-Zug" # FW
      answer: "YES"
    - phrase: "Umwelt" # DLRG
      answer: "YES"
    - phrase: "Ölwehr" # THW
      answer: "YES"
    - phrase: "Umweltschutz" # THW
      answer: "YES"

  - id: "3e3042fa-beca-4d18-bb0c-f6f9a9d8f68f"
    question: "Bist Du handwerklich begabt? Den Umgang mit Kettensäge und Trennschleifer möchtest Du erlernen?"
    description: "Technisches Gerät zur Menschenrettung und Gefahrenabwehr zählt bei einigen Einsatzorganisationen zur Basisausstattung."
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "MAYBE"
    - phrase: "Bergungsgruppe" # THW
      answer: "YES"

  - id: "44d1132f-3407-4387-808d-47368c8d7ffc"
    question: "Hast Du was für Wassersport übrig? Boot fahren, Retten von Menschen aus Gewässern?"
    description: "Möchtest Du Tauchen lernen oder den Bootsführerschein machen? Einige Einsatzorganisationen haben ihren Schwerpunkt im Bereich der Wasserrettung gesetzt und könnten Deine Hilfe gebrauchen."
    defaultAnswer: "NO"
    groups:
    - phrase: "Wassergefahren" # THW
      answer: "YES"
    - phrase: "Rettungsschwimm" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Rettungstaucher" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "wasserrettung" # DLRG / ASB / DRK
      answer: "YES"
    - phrase: "Boot" # DLRG / ASB / DRK / FW / THW
      answer: "YES"

  - id: "b6788fa7-a360-4b65-8055-193c4c40d1f4"
    question: "Magst Du die Bergwelt? Kannst Du Dir vorstellen, hier Menschen zu retten?"
    description: "Die Rettung verletzter Personen auf Skipisten oder im Bergland erfordert spezielle Kenntnisse und gute Konditionen."
    defaultAnswer: "NO"
    groups:
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"
    - phrase: "Höhenrettung" # ASB / DRK / THW
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"

  - id: "ae4cdb0c-c35f-42fe-8996-599bfffc8fc2"
    question: "Betreuung von unverletzten Menschen, mit ihnen sprechen, die wichtigsten Dinge des Lebens organisieren und verteilen - Dein Ding?"
    description: "Gehst Du gerne auf Menschen zu und möchtest in Notlage geratene besonders hilfebedürftiger Personen, wie beispielsweise ältere Menschen, behinderte Personen oder Eltern mit Kleinkindern betreuen?"
    defaultAnswer: "NO"
    groups:
    - organisationType: "FF"
      answer: "MAYBE"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "MAYBE"
    - phrase: "Kriseninterventionsteam" # ASB / DRK
      answer: "YES"
    - phrase: "Betreuung" # DLRG / ASB / DRK
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"

  - id: "c9204024-1399-4b34-b7a4-6919c09cdc41"
    question: "Möchtest Du aktiv als Besatzungsmitglied eines Rettungs- oder Krankentransportwagens mitfahren?"
    description: "Von erfahrenen Kollegen kannst Du hier praxisnah Deine Kenntnisse in medizinischer Versorgung vertiefen. Oder möchtest Du nur Rettungswagen fahren?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"

  - id: "0d76d16a-c640-40ec-af4e-2111ad36ee46"
    question: "Bist Du handwerklich interessiert und kannst Strom, Heizung, Wasser, etc. in Notunterkünften installieren?"
    description: "Im Rahmen des Aufbaus von Notunterkünften im In- und Ausland ist die Bereitstellung von Strom und Wasser erforderlich. Wenn Du bereits handwerkliche Erfahrungen hast oder Dir solche aneignen möchtest, bist Du hier richtig."
    defaultAnswer: "NO"
    groups:
    - phrase: "Bergungsgruppe"
      answer: "YES"
    - phrase: "Technik und Sicherheit" # ASB / DRK
      answer: "MAYBE"
    - organisationType: "FF"
      answer: "MAYBE"

  - id: "18662fa9-a854-4174-9ea9-37bb08c65484"
    question: "Fährst Du gerne Motorrad? Kommst Du auch mit etwas größeren Maschinen klar?"
    description: "Ein Unfall auf der Autobahn mit Verletzten. Schnell entwickelt sich ein Stau. Mit dem mit Blaulicht ausgestatteten Motorrad kommst Du schnell zur Unfallstelle und kannst Hilfe leisten."
    defaultAnswer: "NO"
    groups:
    - phrase: "Motorrad"
      answer: "YES"
    - phrase: "ATV/Quad"
      answer: "YES"

  - id: "e025aa16-4b69-42db-9fce-d34792d99a77"
    question: "Gebrochene Knochen schocken Dich nicht - auf die richtige Behandlung kommt es an. Interesse?"
    description: "Du bist medizinisch interessiert und möchtest in diesem Umfeld bei Unfällen oder Großveranstaltungen professionelle Hilfe leisten?"
    defaultAnswer: "NO"
    groups:
    - phrase: "Sanitätsdienst" # DLRG / ASB / DRK
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "MAYBE"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "MAYBE"

  - id: "82113a83-d99a-4a63-89eb-9e5f4268917b"
    question: "Radlader-, Baggerfahren - schwere Baumaschinen fahren?"
    description: "Zur Unterstützung beispielsweise bei der Brandbekämpfung, bei der Deichverteidigung, der Ladungsbergung oder der Rettung verschütteter Personen kommen Baumaschinen zum Einsatz."
    defaultAnswer: "NO"
    groups:
    - phrase: "Räumen" # THW
      answer: "YES"
    - phrase: "Bagger" # THW
      answer: "YES"
    - phrase: "Drehleiter"
      answer: "MAYBE"

  - id: "4813a002-9c0e-4f29-af0c-26be7c197bea"
    question: "Klettern, Bergsteigen, Verletzte retten - auch aus der Kletterwand? Wäre das etwas für Dich?"
    description: "Die Rettung verunglückter Menschen aus Höhen (Baukran, Sendeanlagen, ...) oder Tiefen (Schächte, Gruben, Höhlen, ...) erfordert gute Kondition und spezielles Wissen, was man Dir gerne vermittelt."
    defaultAnswer: "NO"
    groups:
    - phrase: "Drehleiter" # FW
      answer: "YES"
    - phrase: "Höhenrettung" # FW / THW
      answer: "YES"
    - organisationType: "BW"
      phrase: "Ortsgruppe (Basisausstattung/-Tätigkeit)"
      answer: "YES"
    - phrase: "Hubschraubergestützte Wasserrettung" # DLRG / ASB / DRK
      answer: "MAYBE"

  - id: "2e82c293-1f6a-4b4c-8366-f773d42f1caf"
    question: "Deinen Hund zum Suchhund ausbilden, mit ihm vermisste Menschen orten und retten? Interesse?"
    description: "Die Rettungshundeausbildung ist sowohl für den Hund als auch für den Rettungshundeführer anspruchsvoll. Dank Dir und Deinem Hund können jedoch viele Menschen in hilfloser Lage vor dem sicheren Tod gerettet werden."
    defaultAnswer: "NO"
    groups:
    - phrase: "Ortung Typ A"
      answer: "YES"
    - phrase: "Fachgruppe Ortung"
      answer: "YES"
    - phrase: "Rettungshunde" # DLRG / ASB / BW / DRK
      answer: "YES"
    - organisationType: "BRH"
      phrase: "Staffel"
      answer: "YES"
  picture-sizes:
  - name: icon
    width: 84
  - name: teaser
    width: 1000
    height: 300
  - name: medium
    width: 300
  admin-users:
  - username: admin
    password: ${random.value}
    print-password: true

logging:
  file: ${logging.path:${LOG_TEMP:${java.io.tmpdir:/tmp}}}/helfenkannjeder-helfomat.log

  level:
    de.helfenkannjeder: DEBUG