server:
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
  servlet:
    context-path: /helf-o-mat

elasticsearch:
  index: helfomat
  type:
    organization: organization

googlemaps:
  api-key: ReplaceMe

helfomat.picture:
  picture-folder: pictures/
  picture-sizes:
  - name: icon
    width: 84
  - name: teaser
    width: 1000
    height: 300
  - name: medium
    width: 300

spring.servlet.multipart:
  max-file-size: 7MB
  max-request-size: 7MB

security:
  keycloak:
    client:
      access-token-uri: ${keycloak.auth-server-url}/realms/master/protocol/openid-connect/token
      token-info-uri: ${keycloak.auth-server-url}/realms/master/protocol/openid-connect/token/introspect

logging:
  level:
    root: ERROR
    de.helfenkannjeder: DEBUG