spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

keycloak:
  realm: helfenkannjeder
  resource: helfenkannjeder-web-ui
  auth-server-url: http://keycloak/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username