INSERT INTO tx_helfenkannjeder_domain_model_organisationtype (uid, pid, name, acronym, description, picture, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, namedisplay, pseudo, group_template_categories, fegroup, logos, registerable, hide_in_result, teaser, dummy_organisation)
VALUES (
  1,
  6,
  'Arbeiter-Samariter-Bund',
  'ASB',
  '',
  '',
  1393867114,
  1308445735,
  0,
  0,
  0,
  0,
  '',
  0,
  'ASB',
  0,
  6,
  4,
  '',
  1,
  0,
  '',
  0
), (
  2,
  6,
  'Bayerisches Rotes Kreuz',
  'BRK',
  '',
  '',
  1330267996,
  1308445816,
  0,
  1,
  0,
  0,
  '',
  0,
  '',
  0,
  0,
  0,
  NULL,
  0, 0,
  NULL,
  0
), (
  3,
  6,
  'Bergwacht',
  'BW',
  '',
  '',
  1393867149,
  1308445822,
  0,
  0,
  0,
  0,
  '',
  0,
  'Bergwacht',
  0,
  2,
  6,
  '',
  1,
  0,
  '',
  0
), (
  4,
  6,
  'Deutsche Lebens-Rettungs-Gesellschaft',
  'DLRG',
  '',
  '',
  1393867184,
  1308445832,
  0,
  0,
  0,
  0,
  '',
  0,
  'DLRG',
  0,
  4,
  7,
  '',
  1,
  0,
  '',
  0
), (
  5,
  6,
  'Deutsches Rotes Kreuz',
  'DRK',
  '',
  '',
  1393867227,
  1308445841,
  0,
  0,
  0,
  0,
  '',
  0,
  'DRK',
  0,
  6,
  8,
  '',
  1,
  0,
  '',
  0
), (
  6,
  6,
  'Freiwillige Feuerwehr',
  'FF',
  '',
  '',
  1393867264,
  1308445850,
  0,
  0,
  0,
  0,
  '',
  0,
  'Freiw. Feuerwehr',
  0,
  2,
  9,
  '',
  1,
  0,
  '',
  0
), (
  7,
  6,
  'Johanniter-Unfall-Hilfe',
  'JUH',
  '',
  '',
  1393867322,
  1308445859,
  0,
  0,
  0,
  0,
  '',
  0,
  'JUH',
  0,
  6,
  10,
  '',
  1,
  0,
  '',
  0
), (
  8,
  6,
  'Malteser Hilfsdienst',
  'MHD',
  '',
  '',
  1393867477,
  1308445869,
  0,
  0,
  0,
  0,
  '',
  0,
  'Malteser Hilfsdienst',
  0,
  5,
  11,
  '',
  1,
  0,
  '',
  0
), (
  9,
  6,
  'Notfallseelsorge / Kriseninterventionsteam',
  '',
  '',
  '',
  1312656899,
  1308445875,
  1,
  0,
  0,
  0,
  '',
  0,
  '',
  0,
  0,
  0,
  NULL,
  0,
  0,
  NULL,
  0
), (
  10,
  6,
  'Technisches Hilfswerk',
  'THW',
  '',
  '',
  1393867513,
  1308445883,
  0,
  0,
  0,
  0,
  '',
  0,
  'THW',
  0,
  5,
  12,
  '',
  1,
  0,
  '',
  0
), (
  11,
  6,
  'Sonstige',
  'sonst',
  'Sonstige Hilfsorganisationen',
  '',
  1335274478,
  1313530055,
  0,
  0,
  0,
  0,
  '',
  0,
  'Sonst',
  0,
  0,
  0,
  NULL,
  0,
  0,
  NULL,
  0
), (
  12,
  6,
  'HelfenKannJeder',
  'HKJ',
  'HelfenKannJeder.de ist der gemeinsame Internetauftritt der in der Gefahrenabwehr tätigen Karlsruher Hilfsorganisationen.',
  '',
  1335274497,
  1313530150,
  0,
  0,
  0,
  0,
  '',
  0,
  'HKJ',
  0,
  0,
  0,
  NULL,
  0,
  0,
  NULL,
  0
), (
  15,
  6,
  'Bundesverband Rettungshunde',
  'BRH',
  '',
  '',
  1393867550,
  1370294279,
  0,
  0,
  0,
  0,
  '',
  0,
  'Bundesverband Rettungshunde',
  0,
  2,
  54,
  '',
  1,
  0,
  '',
  0
);

---
--- THW Karlsruhe
---

INSERT INTO tx_helfenkannjeder_domain_model_organisation (uid, pid, name, description, website, street, city, pictures, feuser, groups, employees, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, matrices, zipcode, organisationtype, longitude, latitude, telephone, logo, workinghours, addresses, contactpersons, umbrellaorganisation, nationalassociation, addressappendix, defaultaddress, t3ver_oid, t3ver_id, t3ver_wsid, t3ver_label, t3ver_state, t3ver_stage, t3ver_count, t3ver_tstamp, t3_origuid, hash, reference, is_dummy)
VALUES (
  1,
  6,
  'THW Karlsruhe',
  'Wir sind die Hilfsorganisation des Bundes und unterstützen die für die Gefahrenabwehr zuständigen Stellen auch mit Spezialgerät bei der Bekämpfung von Schadenslagen aller Art. Ein weiterer gesetzlicher Auftrag ist die Leistung von Hilfe im Zivilschutz. Unser Tätigkeitsgebiet beschränkt sich nicht nur auf Deutschland, so haben wir auf zahlreichen Einsätzen rund um den Globus humanitäre Hilfe leisten können. So haben Mitarbeiter des THW Karlsruhe beispielsweise im Nordirak, Ruanda, Somalia und in den Ebola-Gebieten von Sierra Leone Hilfe geleistet. Ihrer besonderen Verantwortung als „humanitäre Botschafter“ Deutschlands sind sich die THW-Angehörigen bei ihrem Engagement im Ausland stets bewusst und schon der Nachwuchs wird bereits in jungen Jahren an diese besondere Rolle herangeführt. Mit der Teilnahme von THW-Jugendgruppen an internationalen Jugendbegegnungen oder dem tunesischen Zivilschutztag leisten schon die Jüngsten einen Beitrag zur Völkerverständigung.',
  'http://www.thw-karlsruhe.de',
  '',
  '',
  '',
  1,
  10,
  9,
  1430916053,
  1333830565,
  0,
  0,
  0,
  0,
  '',
  0,
  8,
  '0',
  10,
  8.352747,
  49.03766,
  '',
  '',
  3,
  1,
  1,
  '',
  '',
  '',
  7,
  0,
  0,
  0,
  '',
  0,
  0,
  0,
  0,
  0,
  '5df4a7d344683cecaa163e0f4d2b84a6',
  1,
  0
);

INSERT INTO tx_helfenkannjeder_domain_model_employee (uid, pid, organisation, rank, surname, prename, motivation, birthday, pictures, mail, street, city, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, mobilephone, headline, iscontact, telephone, reference)
VALUES (
  1,
  6,
  1,
  'Beauftragter für Öffentlichkeitsarbeit',
  'Müller1',
  'David',
  'Viele Menschen, die mein Leben bereichern, hätte ich ohne das THW nie kennengelernt: Mit einem THW-Kollegen habe ich eine Firma gegründet, die im Februar 2011 zehn Jahre alt geworden ist und nun an die 40 Mitarbeiter hat. Seit meinem THW-Auslandseinsatz in Somalia weiß ich, wie gut es uns in Deutschland geht, und möchte das, was ich erhalten habe, der Gesellschaft gerne zurückgeben. Ich bin gerne beim THW, weil es hier ständig Neues zu entecken und zu erleben gibt.',
  -13478400,
  '',
  'no-spam@helfenkannjeder.de',
  '',
  '',
  1347818856,
  1309909349,
  0,
  0,
  0,
  0,
  '',
  0,
  '0123 456789',
  '',
  1,
  '',
  1
), (
  3,
  6,
  1,
  '',
  'Müller2',
  'Lisa',
  'Seit 2006 bin ich beim THW und habe hier schon viele nette Leute kennengelernt. Schön finde ich die Möglichkeit, sich in technischen Themen weiterbilden zu können - eine ideale Ergänzung zum Berufsleben. Schau doch auch vorbei!',
  0,
  '',
  '',
  '',
  '',
  1347818856,
  1309988508,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  3
), (
  2,
  6,
  1,
  '',
  'Müller3',
  'Timo',
  'Der Zusammenhalt und die Kameradschaft sind die Hauptgründe, warum ich im THW bin. Außerdem gibt es mir ein gutes Gefühl, Menschen, die in Not geraten sind, helfen zu können. Dadurch, dass ich hier Verantwortung übernehmen kann, gewinne ich Führungserfahrungen - dieses Wissen ist auch in meinem Job von unbezahlbarem Wert.',
  0,
  '',
  '',
  '',
  '',
  1347818856,
  1309911260,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  4
), (
  4,
  6,
  1,
  '',
  'Müller4',
  'Ilona',
  'Unimog fahren, Rettungsgeräte einsetzen, bei interessanten Übungen mitmachen, im Einsatz Menschen mit technischem Sachverstand helfen - alles Dinge, die man im alltäglichen Leben nicht so machen kann, die aber enorm viel Spaß machen und einen idealen Ausgleich zum Bürojob darstellen. Seit 2009 bin ich dabei und freue mich, mit einem tollen Team gemeinschaftlich Ziele zu erreichen. Mein Wunsch: Mindestes einmal mit dem THW Hilfe im Ausland zu leisten. Und Deiner?',
  0,
  '',
  '',
  '',
  'Karlsruhe',
  1347818856,
  1309989506,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  5
), (
  5,
  6,
  1,
  '',
  'Müller5',
  'Thilo',
  'Ich bin seit 2006 beim THW dabei. Hier habe ich ein neues Hobby und viele neue Freunde gefunden, auf die ich mich nicht nur im Einsatz verlassen kann.',
  0,
  '',
  '',
  '',
  '',
  1347818856,
  1309989684,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  6
), (
  6,
  6,
  1,
  '',
  'Müller6',
  'Steffen',
  'Verantwortung übernehmen zu können, technisches Rettungsgerät einzusetzen und ab und an unter schwerem Atemschutz an die Belastungsgrenzen gehen zu können - das sind nur wenige Punkte, warum ich seit vielen Jahren gerne beim THW bin und die Kameradschaft dort in einem Team von Menschen aus allen möglichen Berufsgruppen genieße.',
  0,
  '',
  '',
  '',
  '',
  1347818856,
  1309991705,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  7
), (
  7,
  6,
  1,
  '',
  '',
  'Carolin',
  'Das THW ist nur für Männer... von wegen. Seit 2009 bin ich dabei und mir macht die Arbeit im Team viel Spaß. Es ist immer wieder spannend, wie man mit einfachen Dingen viel bewirken kann.',
  0,
  '',
  '',
  '',
  'Karlsruhe',
  1347818856,
  1310074539,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  8
), (
  45,
  6,
  1,
  'Stellv. Jugendgruppenleiter',
  'Müller8',
  'Christian',
  '',
  0,
  '',
  'no-spam@helfenkannjeder.de',
  '',
  '',
  1347818856,
  1313584281,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  2,
  '0123 45678',
  2
), (
  143,
  6,
  1,
  '',
  'Müller9',
  'Philipp',
  '',
  0,
  '',
  'no-spam@helfenkannjeder.de',
  '',
  '',
  1347818856,
  1347818856,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  2,
  '',
  172
);


INSERT INTO tx_helfenkannjeder_domain_model_address (uid, pid, organisation, street, city, zipcode, longitude, latitude, telephone, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, addressappendix, reference, website)
VALUES (
  7,
  6,
  1,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  8.352747,
  49.03766,
  '0123 456789',
  1336342055,
  1333818269,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  1,
  ''
);


INSERT INTO tx_helfenkannjeder_domain_model_workinghour (uid, pid, organisation, day, starttimehour, stoptimehour, starttimeminute, stoptimeminute, groups, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, addition, address, reference)
VALUES (
  1,
  6,
  1,
  2,
  19,
  22,
  30,
  30,
  6,
  1347818856,
  1309973354,
  0,
  0,
  0,
  0,
  '',
  0,
  'unregelmäßig (Dienstplan siehe Homepage)',
  0,
  1
), (
  133,
  6,
  1,
  4,
  18,
  19,
  0,
  30,
  1,
  1347818856,
  1347818856,
  0,
  0,
  0,
  0,
  '',
  0,
  'Jeder 1. und 3. Donnerstag im Monat',
  7,
  145
), (
  74,
  6,
  1,
  6,
  8,
  16,
  0,
  0,
  4,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  'unregelmäßig, Termine siehe Homepage',
  7,
  47
);

INSERT INTO tx_helfenkannjeder_domain_model_group (uid, pid, organisation, name, description, minimum_age, maximum_age, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, matrix, longitude, latitude, street, city, zipcode, website, workinghours, sort, contactpersons, template, reference)
VALUES (
  1,
  6,
  1,
  '1. Bergungsgruppe',
  '',
  18,
  65,
  1336291297,
  1305647857,
  1,
  0,
  0,
  0,
  '',
  0,
  2,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  1
), (
  2,
  6,
  1,
  'Fachgruppe Wasserschaden/Pumpen',
  '',
  18,
  65,
  1336291297,
  1306055756,
  1,
  0,
  0,
  0,
  '',
  0,
  1,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  4
), (
  3,
  6,
  1,
  '2. Bergungsgruppe',
  '',
  18,
  65,
  1336291297,
  1307873413,
  1,
  0,
  0,
  0,
  '',
  0,
  2,
  8.35,
  49.04,
  'Grünhutstraße 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  3
), (
  11,
  6,
  1,
  'Fachgruppe Beleuchtung',
  '',
  18,
  65,
  1336291297,
  1307899330,
  1,
  0,
  0,
  0,
  '',
  0,
  14,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  5
), (
  12,
  6,
  1,
  'Fachgruppe Räumen',
  '',
  18,
  65,
  1336291297,
  1307899905,
  1,
  0,
  0,
  0,
  '',
  0,
  15,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  6
), (
  13,
  6,
  1,
  'THW-Jugend',
  '',
  10,
  17,
  1336291362,
  1307900243,
  1,
  0,
  0,
  0,
  '',
  0,
  16,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  1,
  0,
  7
), (
  14,
  6,
  1,
  'THW OV-Stab',
  '',
  18,
  65,
  1336291297,
  1307900839,
  1,
  0,
  0,
  0,
  '',
  0,
  17,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  2
), (
  15,
  6,
  1,
  'Örtliche Gefahrenabwehr',
  '',
  18,
  65,
  1336291325,
  1307901196,
  1,
  0,
  0,
  0,
  '',
  0,
  18,
  8.35,
  49.04,
  'Grünhutstr. 9',
  'Karlsruhe',
  '76187',
  '',
  '',
  1000000000,
  0,
  0,
  8
), (
  90,
  6,
  1,
  'OV-Stab',
  'Der OV-Stab bildet die Verwaltungseinheit eines Ortsverbands und dient der Führung und Organisation. Alle Mitglieder einschließlich des Leiters eines THW-Ortsverbandes (Ortsbeauftragte), sind rein ehrenamtlich tägig.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  17,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  41472,
  0,
  1,
  22
), (
  91,
  6,
  1,
  'Fachgruppe Beleuchtung (FGr Bel)',
  'Die Fachgruppe Beleuchtung macht die Nacht zum Tag. Sie besitzt eine breite Palette von Beleuchtungsmitteln, um Einsatzstellen, Bereitstellungsräume oder Veranstaltungsorte großflächig auszuleuchten.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  14,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  161024,
  0,
  7,
  24
), (
  92,
  6,
  1,
  'Fachgruppe Räumen (FGr R, Typ A und B)',
  'Mit ihren leistungsfähigen Baumaschinen ist die Fachgruppe Räumen an fast allen alltäglichen Einsätzen des THW beteiligt. Häufig kommen die wendigen Radlader zum Einsatz, um die Feuerwehr bei der Brandbekämpfung zu unterstützen. Insbesondere, wenn einsturzgefährdete Gebäude gesichert oder eingerissen, Bauwerksteile niedergelegt oder Trümmer weggeräumt werden müssen, ist diese Einheit eine große Hilfe. Die Einsatzkräfte dieser Fachgruppe unterstützen auch Rettungskräfte, die zu eingeschlossenen oder verschütteten Personen vordringen müssen.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  15,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  154624,
  0,
  15,
  25
), (
  93,
  6,
  1,
  'Zugtrupp',
  'Der Zugtrupp ist für die Koordination von THW-Einsätzen zuständig und richtet in der Regel nahe des Einsatzgeschehens eine Befehlsstelle ein, welche sich mit den Führungsstellen anderer Hilfsorganisationen abstimmt.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  47,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  122880,
  0,
  217,
  26
), (
  94,
  6,
  1,
  '1. Bergungsgruppe',
  'Die 1. Bergungsgruppe (1. BGr) ist die universellste Gruppe im Technischen Zug. Das Personal und die Ausstattung sind auf die Bewältigung eines möglichst breiten Aufgabenspektrums ausgerichtet. Zur Ausstattung gehört ein umfangreiches Sortiment an Werkzeugen und Geräten zur Rettung von Menschen, zur Bearbeitung von Holz, Metall und Stein, zur Sicherung von Personen und Einsatzstellen, zum Trennen, Heben und Bewegen von Trümmern oder Bauteilen sowie zum Bau von Hilfskonstruktionen und anderem mehr.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  2,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  124928,
  0,
  218,
  27
), (
  95,
  6,
  1,
  'Jugendgruppe',
  'Die THW-Jugendgruppe vermittelt Heranwachsenden im Alter von zehn bis 17 Jahren das kleine Einmaleins der Rettungsmethoden mit der Technik, wie sie auch die "alten Hasen" einsetzen auf spannende und spielerische Weise. Hier kann man seine Technik-Begeisterung ausleben und bei Wettkämpfen und realitätsnahen Einsatzübungen seine Fähigkeiten unter Beweis stellen:
Unsere Jugendlichen lernen, wie man einen dunklen Weg ausleuchtet, schwere Lasten bewegt und hilflose Menschen rettet. Mit Funkgeräten koordinieren sie die Zusammenarbeit ihrer Teams beim Aufbau einer Seilbahn oder beim Überwinden von Hindernissen.',
  10,
  17,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  16,
  0,
  0,
  '',
  '',
  '0',
  'http://www.thw-jugend-karlsruhe.de',
  '',
  62464,
  1,
  5,
  23
), (
  96,
  6,
  1,
  'Abstützen',
  'Mit unserem Abstützsystem aus Holzelementen lassen sich Bauwerke bis 15 Meter Höhe wirksam sichern. Der Aufbau des modularen Systems erfolgt in kleinen Höhen manuell, bei weiteren Ausbaustufen mit Hilfe eines Kranes.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  109,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  174336,
  0,
  23,
  121
), (
  97,
  6,
  1,
  'Feldkochherd',
  'Mit unserer mobilen Feldküche sind wir in der Lage, bis zu 120 Personen organisationsintern oder auch bei Veranstaltungen und Festen zu verpflegen.',
  18,
  99,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  116,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  189184,
  0,
  31,
  122
), (
  98,
  6,
  1,
  'Technische Hilfe auf Verkehrswegen (THV-Dienst)',
  'Wir unterstützen die Polizei auf den Bundesautobahnen vor allem in Zeiten mit hohem Verkehrsaufkommen:
- Absicherung von Stau-Enden
- Erstversorgung von Verletzten bei Verkehrsunfällen
- Räumen der Fahrbahn von Unfallfahrzeugen
- Reinigung der Fahrbahn nach Unfällen
Für diese Tätigkeit werden die Einsatzkräfte speziell geschult und nehmen regelmäßig an Fortbildungen im Bereich Absicherung, Gefahren auf der Autobahn und Soforthilfemaßnahmen teil.',
  18,
  65,
  1347818856,
  1336167339,
  0,
  0,
  0,
  0,
  '',
  0,
  127,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  190720,
  0,
  38,
  123
), (
  273,
  6,
  1,
  'Bambini-/Mini-Jugendgruppe',
  'Für Kinder unter zehn Jahren besteht die Möglichkeit, in einer Mini-/Bambini-Jugendgruppe mitzumachen. In dieser wird ein besonderes Betreuungsprogramm für die entsprechende Altersklasse angeboten. Inhalte der Veranstaltungen sind einfachste Techniken des THW wie z. B. die Bedienung von Hebekissen aber auch spielerische Aspekte wie Fahrradtouren, Kanufahrten,  Zeltlager, Erste-Hilfe-Ausbildung und sportliche Aktivitäten.',
  6,
  9,
  1347818856,
  1347818856,
  0,
  0,
  0,
  0,
  '',
  0,
  16,
  0,
  0,
  '',
  '',
  '0',
  'http://www.thw-jugend-karlsruhe.de',
  '',
  89856,
  1,
  6,
  437
);


INSERT INTO tx_helfenkannjeder_group_contactperson_mm (uid, pid, uid_local, uid_foreign, sorting, sorting_foreign, tstamp, crdate, hidden)
VALUES
  (10, 0, 13, 45, 1, 0, 0, 0, 0),
  (16, 0, 95, 45, 1, 0, 0, 0, 0),
  (62, 0, 273, 143, 1, 0, 0, 0, 0);


INSERT INTO tx_helfenkannjeder_organisaton_contactperson_mm (uid, pid, uid_local, uid_foreign, sorting, sorting_foreign, tstamp, crdate, hidden)
VALUES (1, 0, 1, 1, 1, 0, 0, 0, 0);


INSERT INTO tx_helfenkannjeder_workinghour_group_mm (uid, pid, uid_local, uid_foreign, sorting, sorting_foreign, tstamp, crdate, hidden)
VALUES
  (125, 0, 74, 94, 4, 0, 0, 0, 0),
  (124, 0, 74, 93, 3, 0, 0, 0, 0),
  (123, 0, 74, 92, 2, 0, 0, 0, 0),
  (121, 0, 1, 94, 6, 0, 0, 0, 0),
  (120, 0, 1, 93, 5, 0, 0, 0, 0),
  (119, 0, 1, 92, 4, 0, 0, 0, 0),
  (118, 0, 1, 91, 3, 0, 0, 0, 0),
  (117, 0, 1, 95, 2, 0, 0, 0, 0),
  (116, 0, 1, 90, 1, 0, 0, 0, 0),
  (122, 0, 74, 91, 1, 0, 0, 0, 0),
  (321, 0, 133, 273, 1, 0, 0, 0, 0);

---
--- ASB Karlsruhe
---


INSERT INTO tx_helfenkannjeder_domain_model_organisation (uid, pid, name, description, website, street, city, pictures, feuser, groups, employees, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, matrices, zipcode, organisationtype, longitude, latitude, telephone, logo, workinghours, addresses, contactpersons, umbrellaorganisation, nationalassociation, addressappendix, defaultaddress, t3ver_oid, t3ver_id, t3ver_wsid, t3ver_label, t3ver_state, t3ver_stage, t3ver_count, t3ver_tstamp, t3_origuid, hash, reference, is_dummy)
VALUES (
  12,
  6,
  'ASB Karlsruhe',
  'Wir sind in den folgenden Bereichen tätig:

[b]1. Sanitätsbetreuung[/b]
Die Sanitätsbetreuung ist die geplante Betreuung von Veranstaltungen, bei denen auf Grund Ihrer Größe oder Art eine medizinische Versorgung erforderlich ist.
So ist bei Sportveranstaltungen oder Festen ausgebildetes Personal im Einsatz, das für die Sicherheit der Besucher zuständig ist. In eigens eingerichteten Sanitätsstationen werden verletzte oder erkrankte Menschen versorgt. Ist eine Weiterbehandlung in einem Krankenhaus erforderlich, kümmern sich die erfahrenen Helfer um den Abtransport und die Weiterversorgung.

[b]2. Sanitätsdienst[/b]
Im Falle einer Katastrophe, bei der es viele verletzte Menschen gibt, ist auch der Sanitätsdienst gefragt. Die Sanitäterinnen und Sanitäter kümmern sich um erkrankte oder verletzte Menschen, bauen Behandlungsplätze auf und stellen Rettungsfahrzeuge bereit. Sie alle sind ehrenamtlich aktiv und haben für ihre Tätigkeit eine entsprechende Fachdienstausbildung absolviert.

[b]3. Schnell-Einsatz-Gruppe (SEG)[/b]
Schnell-Einsatz-Gruppen (SEG) haben gegenüber den regulären Einheiten des Katastrophenschutzes eine deutlich kürzere Vorlaufzeit von der Alarmierung bis zum Eintreffen am Einsatzort. Schnelleinsatzgruppen mit Ausrichtung auf den Sanitätsdienst existieren bereits seit geraumer Zeit und an vielen Standorten in Deutschland.

In Karlsruhe stellt der ASB drei verschiedene Schnelleinsatzgruppen:
[list][*]SEG Rettungsdienst (rettungsdienstlich ausgebildete Einsatzkräfte mit entsprechenden Fahrzeugen und Materialien des Rettungsdienstes zur Unterstützung und Ergänzung des Regelrettungsdienstes
[*]SEG Betreuung (ausgebildete Helfer zur Betreuung von unverletzten Betroffenen und Angehörigen)
[*]SEG Notarzt (Notärzte mit Assistenzpersonal für große Schadenslagen)[/list]

[b]4. Notfallhilfe[/b]
Um den Zeitraum zwischen einem Unfall und dem Eintreffen des Rettungsdienstes zu überbrücken werden First Responder eingesetzt. Mit qualifizierten Basismaßnahmen stabilisieren die erfahrenen Rettungs- und Sanitätsdienstmitarbeiter des ASB die Patienten und sorgen damit für eine optimale Versorgung im Notfall.
Der ASB RV Karlsruhe hält im Albtal die Notfallhilfe Marxzell vor, deren Ausrückbereich Marxzell und die anhängigen Ortschaften umfasst. Auch die "Albtalstrecke", eine unfallträchtige, stark frequentierte Landesstraße befindet sich zum Teil im Zuständigkeitsbereich der Notfallhilfe Marxzell.

[b]5. Rettungshundestaffel[/b]
Die Rettungshunde des ASB sind bei der Suche nach Vermissten oder verunglückten Menschen unersetzlich. Jede Rettungshundestaffel wird von der Polizei alarmiert und kann innerhalb kürzester Zeit zu einer Suchaktion ausrücken.
Der ASB Karlsruhe baut derzeit eine eigene Rettungshundestaffel auf.

[b]6. Motorradstaffel[/b]
Wird schnelle Hilfe benötigt und ist aufgrund der örtlichen Gegebenheit ein Durchkommen mit Rettungswagen nur schwer möglich, wird die Motorradstaffel des ASB RV Karlsruhe eingesetzt.
Erfahrene Mitarbeiter des Rettungs- und Sanitätsdienstes unterstützen so den Regelrettungsdienst im Rahmen der Erstversorgung, aber auch die Sanitätsdienste bei Großveranstaltungen. Mit speziell ausgestatteten Motorrädern sind die Einsatzkräfte schnell bei den Patienten und können so eine qualifizierte Erstversorgung garantieren.
Daneben sind die Motorräder für Logistikaufgaben und Erkundungsaufgaben geeignet und werden hierfür von der Rettungsleitstelle Karlsruhe gerne eingesetzt.
Die Motorräder sind von März bis Oktober an den Wochenenden im Bereich der stark frequentierten Autobahnen und Bundesstraßen in der Region Karlsruhe unterwegs. In Zusammenarbeit mit der Autobahnpolizei leisten sie auch hier Erste Hilfe und sichern bis zum Eintreffen weiterer Kräfte Unfallstellen und/oder Pannenfahrzeuge ab.',
  'http://www.asb.de/karlsruhe',
  '',
  '',
  '',
  14,
  12,
  4,
  1394210048,
  1333833226,
  0,
  0,
  0,
  0,
  '',
  0,
  1,
  '0',
  1,
  8.46861,
  49.00378,
  '',
  '',
  1,
  1,
  1,
  '',
  '',
  '',
  12,
  0,
  0,
  0,
  '',
  0,
  0,
  0,
  0,
  0,
  '4ad98252c8a3ae1bcfb20d0b002bfc16',
  6,
  0
);


INSERT INTO tx_helfenkannjeder_domain_model_address (uid, pid, organisation, street, city, zipcode, longitude, latitude, telephone, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, addressappendix, reference, website)
VALUES (
  12,
  6,
  12,
  'Pforzheimer Straße 27 a',
  'Karlsruhe',
  '76227',
  8.46861,
  49.00378,
  '0123 456789',
  1383071629,
  1333818595,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  11,
  ''
);


INSERT INTO tx_helfenkannjeder_domain_model_employee (uid, pid, organisation, rank, surname, prename, motivation, birthday, pictures, mail, street, city, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, mobilephone, headline, iscontact, telephone, reference)
VALUES (
  8,
  6,
  12,
  '',
  'Müller10',
  'Matthias',
  'Ich bin seit meinem zehnten Lebensjahr in einer Hilfsorganisation und seit 1992 beim ASB. Ich engagiere mich beim ASB, weil ich schon immer Menschen helfen wollte und weil es Spaß macht, mit verschiedenen Charakteren zusammenzuarbeiten.',
  0,
  '',
  '',
  '',
  '',
  1333833226,
  1312643743,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  26
), (
  9,
  6,
  12,
  '',
  '',
  'Miriam',
  'Seit 2009 bin ich ehrenamtliches Mitglied beim ASB in Karlsruhe. Durch den Ersten-Hilfe-Kurs für meinen Führerschein kannte ich den ASB. Kurze Zeit später musste ich das Gelernte anwenden, da eine Bekannte von mir sich verletzt hatte. Der angeforderte Rettungswagen kam vom ASB und der Umgang und die Art der Betreuung durch die beiden Rettungsassistenten fand ich so positiv, dass auch ich Lust hatte, einer dieser Menschen zu werden, der anderen helfen kann.
Nachdem ich mich im Internet über den ASB informiert hatte, bin ich zu einem Ausbildungsabend des Sanitätsdienstes gegangen. Seither habe ich bei Sanitätsdiensten geholfen, die immer viel Spaß machen, da man bei verschiedensten Einsatzorten und mit netten Kollegen arbeitet... und natürlich da ist, um Menschen zu helfen, die sich verletzt haben oder denen es in dem Moment nicht gut geht. 
Außerdem gibt mir der ASB die Möglichkeit mich weiterzubilden - derzeit mache ich gerade den Rettungssanitäter, was auf jeden Fall sehr spannend ist.',
  0,
  '',
  '',
  '',
  '',
  1333833226,
  1312643948,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  27
), (
  10,
  6,
  12,
  '',
  'Müller12',
  'Stefan',
  'Ich engagiere mich seit 2006 ehrenamtlich beim ASB in Karlsruhe. Dazugekommen bin ich durch meine Verpflichtung im Katastrophenschutz als Wehrersatzdienstleistender.
Heute verbringe ich meine Zeit gerne beim ASB Karlsruhe, um neu gewonnene Freunde zu treffen, Spaß zu haben, mich medizinisch weiterzubilden und natürlich um anderen im Notfall adäquat Hilfe leisten zu können.',
  0,
  '',
  '',
  '',
  '',
  1333833226,
  1312644038,
  0,
  0,
  0,
  0,
  '',
  0,
  '',
  '',
  0,
  '',
  28
), (
  27,
  6,
  12,
  '',
  'Müller13',
  'Carsten',
  '',
  0,
  '',
  'no-spam@helfenkannjeder.de',
  'Pforzheimerstraße 27a',
  '76227 Karlsruhe',
  1333833226,
  1312661854,
  0,
  0,
  0,
  0,
  '',
  0,
  '01234/56789',
  '',
  0,
  '',
  25
);

INSERT INTO tx_helfenkannjeder_domain_model_group (uid, pid, organisation, name, description, minimum_age, maximum_age, tstamp, crdate, deleted, hidden, sys_language_uid, l18n_parent, l18n_diffsource, access_group, matrix, longitude, latitude, street, city, zipcode, website, workinghours, sort, contactpersons, template, reference)
VALUES (
  685,
  6,
  12,
  'Ortsverband allgemein',
  'Unsere Aktivitäten sind vielfältig:
Sanitäter und Ersthelfer stehen bei vielen öffentlichen Veranstaltungen wie Fußballspiele oder Popkonzerten bereit.
Eine abgeschlossene Sanitätsausbildung
reicht für die vielfältigen Aufgaben nicht aus.
Sprechfunkausbildung, Frühdefibrillation, Betreuungsdienst-Grundausbildung sowie Technik und Sicherheit und Strom im Einsatz gewährleisten Deine universelle Einsetzbarkeit.',
  18, 65, 1383071629, 1383071629, 0, 0,
  0,
  0,
  '',
  0,
  74,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  21504,
  0,
  115,
  884
), (
  767,
  6,
  12,
  'Schnelleinsatzgruppe (SEG)',
  'Die Schnell-Einsatz-Gruppe (SEG) unterstützt den Rettungsdienst bei Engpässen, insbesondere dann, wenn viele Menschen von einem Unglück oder einer plötzlichen Erkrankung betroffen sind. Die ehrenamtlichen Helfer des Sanitätsdienstes sorgen für die schnelle und kompetente Versorgung bei Verletzungen und Erkrankungen.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  55,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  65792,
  0,
  116,
  885
), (
  768,
  6,
  12,
  'Notfallhilfe (First Responder)',
  'Um vor allem im ländlich strukturierten Gebieten die oftmals langen Anfahrtszeiten des Rettungsdienstes zu überbrücken bzw. bei Spitzenbelastungen auszugleichen, sollen First-Responder-Teams das so genannte therapiefreie Intervall bis zum Eintreffen professioneller Hilfe überbrücken. Diese Einrichtung stellt keine Konkurrenz zum öffentlichen Rettungsdienst dar.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  55,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  83200,
  0,
  142,
  886
), (
  769,
  6,
  12,
  'Kameradschaftsabend',
  'Unsere Gruppen treffen sich regelmässig in unserer Hauptwache in Durlach. Aus- und Fortbildung stehen neben der kameradschaftlichen Zusammenkunft hier im Vordergrund. ',
  16,
  99,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  94,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  112128,
  0,
  230,
  887
), (
  770,
  6,
  12,
  'Erste-Hilfe-Ausbildung',
  'Du kannst Dich bei uns zum Erste Hilfe Ausbilder weiterqualifizieren. Nach Abschluß dieser Ausbildung und ggf. weiterere Fortbildungen bildest Du Ersthelfer in den folgenden Kursen aus:
- Lebensrettende Sofortmaßnahmen (8 Stunden)
- Erste-Hilfe-Lehrgang (16 Stunden)
- Erste-Hilfe-Training (8 Stunden)
- Erste-Hilfe-Aufbaulehrgang (24 Stunden)
- Erste Hilfe bei Kindernotfällen (10 Stunden)
- Herz-Lungen-Wiederbelebung (8 Stunden)
- Medizinische Erstversorgung für Schüler (12 Stunden)
- Ausbildung in Defibrillation (unterschiedlicher Stundenumfang)
- Ausbildung zum Betriebssanitäter (68 und 32 Stunden)',
  10,
  99,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  59,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  135424,
  0,
  138,
  888
), (
  771,
  6,
  12,
  'Sanitätsausbildung',
  'Wir bilden unsere haupt- und ehrenamtlichen Mitarbeiter selbstverständlich selbst aus und bieten neben der sanitätsdienstlichen Ausbildung auch die Möglichkeit der Ausbildung zum(zur) Rettungssanitäter/in. ',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  61,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  145920,
  0,
  139,
  889
), (
  772,
  6,
  12,
  'Sanitätsdienst',
  'Der Sanitätsdienst leistet der betroffenen Bevölkerung im Schadensgebiet Hilfe, führt ärztliche Sofortmaßnahmen zur Abwendung lebensbedrohlicher Zustände und zur Herstellung der Transportfähigkeit durch.

Er rettet, sichtet, registriert und versorgt Patienten. Der Sanitätsdienst transportiert Patienten und unterstützt andere Einheiten. Bei größeren Schadenslagen betreibt der Sanitätsdienst zusammen mit dem Betreuungsdienst entsprechende Behandlungsplätze.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  82,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  165120,
  0,
  120,
  890
), (
  773,
  6,
  12,
  'Betreuungsdienst',
  'Der Betreuungsdienst sorgt dafür, dass die von einem Großschadensereignis- oder einer Gefahrenlage betroffenen Menschen betreut werden. Das umfasst die vorübergehende Unterbringung, die Verpflegung sowie die psychische und soziale Betreuung der Betroffenen, beispielsweise während eines Sturms, einer Flut oder nach einer Massenkarambolage auf der Autobahn.

Der Betreuungsdienst unterstützt den Sanitätsdienst bei seinen Aufgaben und betreibt mit ihm zusammen Behandlungsplätze zur Versorgung und Betreuung von Verletzten und Betroffenen aus größeren Schadenslagen.',
  18,
  99,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  75,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  182272,
  0,
  118,
  891
), (
  774,
  6,
  12,
  'Technik und Sicherheit',
  'Der Trupp Technik und Sicherheit stellt die Strom- und die Wasserversorgung sicher und sorgt dafür, dass Einsatzstellen abgesichert werden.
Hinzu kommt die Versorgung mit Verbrauchsgütern (Kraftstoff) sowie kleinere handwerkliche Verrichtungen.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  84,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  184064,
  0,
  121,
  892
), (
  775,
  6,
  12,
  'Rettungshunde',
  'Du liebst Hunde über alles und möchtest mit Deinen vierbeinigen Freund Menschenleben retten? Hunde haben im Vergleich zum Menschen ein rund eine Million besseres Riechvermögen. Da die Hundenase rechts und links differenzieren kann, können Hunde ''Stereo'' riechen. Auf diese Weise ist der Hund fähig, Menschen räumlich zu ''erschnuppern''. Auch wenn der Hund mit solchen Fähigkeiten ausgebildet ist, muss ihm beigebracht werden, wie er diese einsetzen kann, denn er muss in der Lage sein, zwischen Verstorbenen und Lebenden zu unterscheiden, die unter Trümmern z. B. nach Gebäudeeinstürzen schnell gerettet werden müssen, denn die Überlebenschancen sinken von Stunde zu Stunde rapide. Wenn Du mit Deinem Vierbeiner helfen möchtest und einem Team Gleichgesinnter beitreten möchtest, bist Du bei einer Hilfsorganisation mit Rettungshunden gut aufgehoben.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  81,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  189952,
  0,
  122,
  893
), (
  776,
  6,
  12,
  'Motorradstaffel',
  'Die Motorradstaffel kommt bei Großveranstaltungen, wie z.B. Marathonläufen, Radrennen, Konzerten, Stadtfesten, Motorradtreffen oder Fußballspielen zum Einsatz, da so die Hilfsfrist wesentlich verkürzt und hierdurch eine schnelle fachgerechte Erstversorgung von Verletzten und Notfallpatienten ermöglicht werden kann. In der Ferien- und Reisezeit sind wir auf den Autobahnen unterwegs.

Zur Basisausrüstung auf allen Motorrädern gehören ein Notfallkoffer, EKG mit Defibrillator, Funk, Schienenmaterial sowie Kinderspielzeug. Hauptaufgabe unserer Motorradstaffel ist auch die Absicherung von Gefahrenstellen auf den Autobahnen der Region. Hier sind wir unterstützend für die Autobahnpolizei tätig. ',
  25,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  80,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  195840,
  0,
  126,
  894
), (
  777,
  6,
  12,
  'Rettungsdienst',
  'Die Mitarbeiter/innen des unseres Rettungsdienstes haben mindestens eine Ausbildung zum Rettungssanitäter, die meisten sind sogar Rettungsassistenten. Wir achten bei der Personalauswahl nicht nur auf Fachwissen, sondern auch auf soziale Kompetenz und Teamfähigkeit. In Karlsruhe und Umgebnung stellen wir fünf Rettungswagen, ein Notarzteinsatzfahrzeug und einen Krankentransportwagen. Somit sind wir nach dem DRK der größte Rettungsdienstleister der Region Karlsruhe.',
  18,
  65,
  1394210048,
  1394210048,
  0,
  0,
  0,
  0,
  '',
  0,
  82,
  0,
  0,
  '',
  '',
  '0',
  '',
  '',
  199168,
  0,
  127,
  895
);
