server:
  context-path: /api

elasticsearch:
  index: helfomat
  type:
    organisation: organisation

spring:
  data:
    elasticsearch:
      cluster-name: application
      cluster-nodes: localhost:9300

helfomat:
  pictureFolder: pictures/