spring:
  profiles:
    active: mock-google-maps
  data:
    elasticsearch:
      cluster-name: application
      cluster-nodes: localhost:9300

server:
  context-path: /api

elasticsearch:
  index: helfomat
  type:
    organisation: organisation

googlemaps:
  apiKey: ReplaceMe
