version: '2.2'

services:
  mysql:
    image: mysql:latest
    container_name: helfomat-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: helfenkannjeder
      MYSQL_DATABASE: helfenkannjeder
      MYSQL_USER: helfenkannjeder
      MYSQL_PASSWORD: helfenkannjeder

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: helfomat-elasticsearch
    environment:
    - cluster.name=application
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - elastic:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300

  postgres:
    image: postgres:12-alpine
    container_name: helfomat-postgres
    environment:
      POSTGRES_USER: helfenkannjeder
      POSTGRES_PASSWORD: helfenkannjeder
      POSTGRES_DB: helfenkannjeder
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
volumes:
  elastic:
  postgres: