version: '2.2'

services:
  mysql:
    image: mysql:latest
    container_name: helfomat-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: helfenkannjeder
      MYSQL_DATABASE: helfenkannjeder
      MYSQL_USER: helfenkannjeder
      MYSQL_PASSWORD: helfenkannjeder

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: helfomat-elasticsearch
    environment:
    - cluster.name=application
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300

  zoo1:
    image: zookeeper:3.4.9
    container_name: helfomat-zookeeper1
    hostname: zoo1
    ports:
    - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
    - ./data/zoo1/data:/data
    - ./data/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka1
    container_name: helfomat-kafka1
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
    - zoo1
