spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/helfenkannjeder
    username: helfenkannjeder
    password: helfenkannjeder

  data:
    elasticsearch:
      cluster-name: application
      cluster-nodes: localhost:9300

  elasticsearch:
    jest:
      uris: http://localhost:9200
      read-timeout: 10000