helfomat:
  hosts:
    dev.helf-o-mat.local:
      ansible_user: root
  vars:
    helfomat_hostname: dev.helf-o-mat.local
    helfomat_config: RUN_ARGS="--spring.datasource.password=PASSWORD --googlemaps.api-key=API_KEY"